### ISSUE TITLE
search function for Uniprot returns different output than the website

### ISSUE THREAD

**Issue by willigott** [cokelaer/bioservices#109]
I parse the catalytic activity of a certain gene like this:

```
from bioservices import UniProt

uni_con = UniProt()
ac = uni_con.search("P30520", columns='comment(CATALYTIC ACTIVITY)')
print(ac)
```

This will print

```
Catalytic activity
CATALYTIC ACTIVITY: GTP + IMP + L-aspartate = GDP + phosphate + N(6)-(1,2-dicarboxyethyl)-AMP. {ECO:0000255|HAMAP-Rule:MF_03127}.
CATALYTIC ACTIVITY: S-adenosyl-L-methionine + L-lysine-[histone] = S-adenosyl-L-homocysteine + N(6)-methyl-L-lysine-[histone].
```
However, when I compare this to the entry on the [website](http://www.uniprot.org/uniprot/P30520) I notice a difference: there is only one reaction listed and not two:

![p30520](https://user-images.githubusercontent.com/10599170/32501505-7ab8ff9c-c3d8-11e7-8fd4-d9e8dcef7b6d.PNG)

What is the reason for that?

Another example:

`print(uni_con.search("P80210", columns='comment(CATALYTIC ACTIVITY)'))`

will print

```
Catalytic activity
CATALYTIC ACTIVITY: GTP + IMP + L-aspartate = GDP + phosphate + N(6)-(1,2-dicarboxyethyl)-AMP. {ECO:0000255|HAMAP-Rule:MF_03125}.
CATALYTIC ACTIVITY: S-ubiquitinyl-[E2 ubiquitin-conjugating enzyme]-L-cysteine + [acceptor protein]-L-lysine = [E2 ubiquitin-conjugating enzyme]-L-cysteine + N(6)-ubiquitinyl-[acceptor protein]-L-lysine.
```

but the second reaction can again not be found on [the website](http://www.uniprot.org/uniprot/P80210).

**Comment by cokelaer** [comment]
Interesting. Well, the data (comment(catalytic)) is definitely fetched from the website. However, it looks like the website does not print all the information found via the webservices. Maybe it is a bug on the uniprot website or intended behaviour. You could contact uniprot guys at http://www.uniprot.org/contact ?

**Comment by willigott** [comment]
Thanks for the quick reply! Where at the website do you retrieve the data from? When I check the page source I do find only one reaction, e.g.

> typeof="schema:CreativeWork"><span property="schema:text">GTP + IMP + L-aspartate = GDP + phosphate + N<sub>6</sub>-(1,2-dicarboxyethyl)-AMP.<span class="attribution ECO255"><span class="attributionHeader ">

I will contact them, but it would be nice if I could point them to a part of their page and say 'there you have two reactions stored for the gene but you display only one part of it on the actual website', however, I have no idea where this second reaction comes from, so if you could tell me where to look or provide a link, this would help me a lot, thanks!

**Comment by willigott** [comment]
Ok. I contacted them and let you know when/if I receive a reply.

**Comment by cokelaer** [comment]
thanks a lot for contacting them. Looking forward for the answer.

**Comment by elisabeth-uniprot** [comment]
Hello, could you please specify which official web service from UniProt you are using to retrieve this data?
I can only see one catalytic activity, as stated by willigot.
Thanks!

**Comment by cokelaer** [comment]
http://www.uniprot.org/uniprot

Note the http. Maybe this should now be https (I believe all EBI services have recently changed to https ?)

The entire URL for the request mentionned by willigot looks like (sorry it is a bit criptic due to the encoding but you get the idea):

```
http://www.uniprot.org/uniprot/?columns=comment%28CATALYTIC+ACTIVITY%29&format=tab&query=P30520&sort=score
```

**Comment by elisabeth-uniprot** [comment]
Thanks for clarifying.
First of all, http is still correct. The UniProt website is not an EBI service, it is maintained by the UniProt Consortium whose members are EBI, SIB and PIR. We'll move to https in the near future, but for the moment it is correct to use http.

I understand what happened with your query. You are doing  a full text search for P30520. This returns 3 entries, as you can see if you include the column "id" in your output:
http://www.uniprot.org/uniprot/?columns=id,comment(CATALYTIC+ACTIVITY)&format=tab&query=P30520&sort=score
`Entry	Catalytic activity
P30520	CATALYTIC ACTIVITY: GTP + IMP + L-aspartate = GDP + phosphate + N(6)-(1,2-dicarboxyethyl)-AMP. {ECO:0000255|HAMAP-Rule:MF_03127}.
Q8NB12	CATALYTIC ACTIVITY: S-adenosyl-L-methionine + L-lysine-[histone] = S-adenosyl-L-homocysteine + N(6)-methyl-L-lysine-[histone].
G7ZES1`

2 of the 3 entries have a catalytic activity. The second line in your output concerns Q8NB12 , an interaction partner of P30520	

I strongly recommend using id:P30520 in order to search by identifier instead of submitting a full text search:
http://www.uniprot.org/uniprot/?columns=id,comment(CATALYTIC+ACTIVITY)&format=tab&query=id:P30520&sort=score

Please don't hesitate to contact the UniProt helpdesk if you have any additional questions.

**Comment by cokelaer** [comment]
Thanks Elisabeth, this makes sense. Our API for this function is indeed a full text search. So, the output is logical (in my opinion). 

@willigot, one solution is to use the parameter limit=1 that will return the most relevant result (here your ID) or indeed as Elisabeth, suggested, if yo uwant just one result, you should preprend the query with "id:" ; for example:

```
from bioservices import UniProt
uni_con = UniProt()
ac = uni_con.search("id:P30520", columns='comment(CATALYTIC ACTIVITY)')
print(ac)
```

**Comment by elisabeth-uniprot** [comment]
I would indeed recommend using id:... rather than limit=1. While in principle, the first result should be the one you are looking for, there is no guarantee. We try our best to establish a ranking that shows the most significant results first, but it is much safer not to rely on this but to be as specific as possible in your query.

**Comment by cokelaer** [comment]
Thanks for the clarification.

**Comment by willigott** [comment]
@cokelaer, @elisabeth-uniprot Thank you both for the detailed explanations! I will give it a try and report back whether that now solves the issues.

**Comment by willigott** [comment]
The suggested solution to use an additional `id:`

```
from bioservices import UniProt
uni_con = UniProt()
ac = uni_con.search("id:P30520", columns='comment(CATALYTIC ACTIVITY)')
print(ac)
```

seems to work very fine for all the examples I tested and where I encountered problems before. I therefore close the issue.

Thanks to both of you for looking into this!
