### ISSUE TITLE
KEGG.get output inconsistency with disease query

### ISSUE THREAD

**Issue by makenzi-n** [cokelaer/bioservices#137]
Hi!
First I'd like to thank you for maintaining such an awesome library – it's made large parts of my thesis possible. 
I encountered a strange behavior with `get() `given a specific query, `H00165`. 
The `GENE` field seems truncated with respect to the disease subtypes:

`get(""H00165")`:

> GENE (Type I) FAH; fumarylacetoacetate hydrolase [HSA:2184] [KO:K01555]
>             (Type II) TAT; tyrosine aminotransferase [HSA:6898] [KO:K00815]
>             (Type III) HPD; 4-hydroxyphenylpyruvate dioxygenase [HSA:3242] [KO:K00457]

`get(""H00165",parse=True)["GENE"]`:

> {'(Type':III) HPD; 4-hydroxyphenylpyruvate dioxygenase [HSA:3242] [KO:K00457]'}

I'm using Bioservices 1.5.2 installed via pip(8.1.2) on Python 3.5.2 via iPython 4.2.0 on OS X 10.11.6.
Is this a known issue and if so, are there any workarounds?
Thanks!

**Comment by mbongaerts** [comment]
Besides you have a double "" in your code above, I get the same result. Something should be wrong with the parser function.

**Comment by cokelaer** [comment]
Fixed in the master of this github. New version of bioservices will include this fix. I have not yet planned a release on bioconda but will most probably push a release on pypi after fixing others small bugs reported in the github. THanks for your bug report. @makenzi-n thanks for using bioservices ! I'm glad it is useful !
