### ISSUE TITLE
Catalytic entities

### ISSUE THREAD

**Issue by MALucabarajas** [cokelaer/bioservices#146]
Hello! I'm a spanish master's student (Bioinfomatics master), and I'm trying to develop my master thesis with the Reactome database. However, I found some problems that I can't resolve. I hope you could help me. I'm using the packages bioservices of Python, and I have problems with some parts of the information obtained. For example, if I use the function "data_entity_componentOf" for the entity "R-HSA-5696021.3" called ADPGK:Mg2+, it doesn't give me any results. And I don't know why, because in the diagram appears that it participates in the pathway _ADPGK:Mg2+ phosphorylates Glc to G6P_ ("R-HSA-5696021.3"). The other problem I found is that I don't know how to obtain the number of molecules of the same type that participates in a reaction. In the description of the diagram it appears, but it's imposible to extract this information with bioservices because each participant only appears once for a reaction.

PD: Sorry for my english, and thanks in advance.

**Comment by cokelaer** [comment]
Dear @MALucabarajas 
Sorry for the late reply. It seems to work for me:
```
from bioservices import Reactome
r = Reactome()
r.data_entity_componentOf("R-HSA-5696021.3")
```
returns
```
[{'names': ['Glycolysis'],
  'schemaClasses': ['Pathway'],
  'stIds': ['R-HSA-70171'],
  'type': 'hasEvent'}]
```

When using 
```
 r.exporter_diagram("R-HSA-70171", filename="test.png")
```

We can see that ADPGK:Mg2+ is in the pathway. 

![test](https://user-images.githubusercontent.com/778821/75122123-ba5f9500-569a-11ea-9ffa-1ffe1f3a3e21.png)

The reactome module in bioservices is a wrapper around reactome. For this type of questions, I am sorry to say that it will be difficult for me to answer to it in details. Maybe it is worth contacting reactome directly. I'm closing this issue since I will not be able to answer in more depth to your questions. thanks for your interest in bioservices.
