### ISSUE TITLE
KEGG.parse does not work for all organisms

### ISSUE THREAD

**Issue by shashany** [cokelaer/bioservices#151]
Hi,
I've tried kegg.parse on pathway entries for different organisms. The parse function worked fine on organisms like eco, mmu, hsa and created a dictionary, but did not work on others such as cit, pmm, ath and prt (the string did not convert into a dictionary).

Here's the code I used:
from bioservices import *
s = KEGG()
s.organism='ath'
paths=s.pathwayIds
for p in paths:
    dict= s.parse(s.get(p))

I'm using pycharm with a python 3.7 interpreter.
Thanks,
Shany

**Comment by cokelaer** [comment]
This is fixed in version 1.7.0 currently being released. Not yet on pypi but on the master branch. The parser was searching for a ; character, which happen to be missing from time to time. There was also an underlying bug since e.g. 
```
'AT5G09600 SDH3-1; succinate dehydrogenase 3-1 [KO:K00236]
```
So the name was **AT5G09600 SDH3-1** wheras it should be  **AT5G09600**.
So, your issue actually found a bug, which is now fixed for all organisms. Thanks for reporting this.
