### ISSUE TITLE
Retrieve ChemBL drug information from target ID

### ISSUE THREAD

**Issue by CryoSky** [cokelaer/bioservices#162]
Hello,
I have a list of ChemBL ID that represents many proteins. I want to know how to find the corresponding drugs/small molecules that bind to those proteins. However, from your document I really don't understand how to do this.

nodelist = ['CHEMBL1163125', 'CHEMBL2095186']

chembl_id_list = []
for node in nodelist:
    print(node)
    c = ChEMBL()
    res = c.get_compound_record(filters="target_chembl_id__in=%s" %node)

My code like this but it always only get one result no matter which node I use.

**Comment by Erik-White** [comment]
I'm not sure what exactly which details you need for the binding drugs/molecules, but here's a working example that I adapted from your code to retrieve the ChemBL IDs

```
from bioservices.chembl import ChEMBL

c = ChEMBL()
proteins = ['CHEMBL1163125', 'CHEMBL2095186']

protein_binding_molecules = dict()
molecule_ids = list()
for protein in proteins:
    binding_molecules = c.get_compound_record(filters="target_chembl_id__in=%s" %protein)
    # binding_molecules will be a list of dictionaries
    # Each dictionary contains the full details
    # Retrieve just the CHEMBL id of each
    molecule_ids = [molecule["molecule_chembl_id"] for molecule in binding_molecules]
    # Store the ids in a dictionary with the target protein as the key
    protein_binding_molecules[protein] = molecule_ids
```

This gives you a dictionary, `protein_binding_molecules`, where the keys are your original protein IDs and the values are a list of binding IDs:
```
CHEMBL1163125 ['CHEMBL3349687', 'CHEMBL3349799', 'CHEMBL3349688', 'CHEMBL3349660', 'CHEMBL3350012', 'CHEMBL3349619', 'CHEMBL3350013', 'CHEMBL3350016', 'CHEMBL3349462', 'CHEMBL3349511', 'CHEMBL3349620', 'CHEMBL3349531', 'CHEMBL3349990', 'CHEMBL3349994', 'CHEMBL3349572', 'CHEMBL3349995', 'CHEMBL3349683', 'CHEMBL3349998', 'CHEMBL3349798', 'CHEMBL3349686']
CHEMBL2095186 ['CHEMBL3349687', 'CHEMBL3349799', 'CHEMBL3349688', 'CHEMBL3349660', 'CHEMBL3350012', 'CHEMBL3349619', 'CHEMBL3350013', 'CHEMBL3350016', 'CHEMBL3349462', 'CHEMBL3349511', 'CHEMBL3349620', 'CHEMBL3349531', 'CHEMBL3349990', 'CHEMBL3349994', 'CHEMBL3349572', 'CHEMBL3349995', 'CHEMBL3349683', 'CHEMBL3349998', 'CHEMBL3349798', 'CHEMBL3349686']
```

Note that `get_compound_record` has a default limit of 20 returned items. You can remove the limit by setting it to -1, but I wouldn't recommend trying it because the whole list will be absolutely massive. You could either chop up the query into smaller parts using the `offset` argument and a loop, or (preferably) narrow down your search.

**Comment by cokelaer** [comment]
@Erik-White thanks a lot. I will close this issue. i believe you answered correctly to it ! thanks again

**Comment by Erik-White** [comment]
Great, thanks Thomas
