### ISSUE TITLE
FASTA class has hardcoded Uniprot

### ISSUE THREAD

**Issue by antonkulaga** [cokelaer/bioservices#172]
FASTA class is very weird, you hardcoded using Uniprot on fasta.get_fasta(id) which is extremely counterintuitive as FASTA format is used pretty much for everything (not only uniprot proteins).
You also use a lot of side-effects and a shared mutable state without any need for doing it. I mean if I receive something from the API call I assume it should be immutable unless there is an explicit mention of its mutability (see biopython Seq and MutableSeq for instance), with your library it is not the case - you mutate fields inside of the returned classes (i.e. FASTA).

**Comment by cokelaer** [comment]
You are probably right, I wrote this class a long time ago and is used for the documentation but also in some codes here and there. So indeed, it loads fasta from uniprot only. I will keep it for now since I know it is used by some people (and myself). Bioservices is about services. It is not meant to replace BioPython or other software dedicated to NGS analysis so I would strongly recommend you to use BioPython for multifasta or fasta manipulation, or even better new software such as scikit-bio or others. 

Thanks for reporting this. I'm closing this issue, since I will not fix it. I would rather get rid of the apps module anyway. I've update the roadmap for v1.8.0 to keep that in mind.
best
