### ISSUE TITLE
Can one save the output of show_pathway as png?

### ISSUE THREAD

**Issue by willigott** [cokelaer/bioservices#194]
I am wondering how to save the output of `show_pathway` as png. For example, when I have 
```

from bioservices import KEGG

s = KEGG()
s.show_pathway('ko02024', keggid=['K07173'])
```

how can I save the outcome to a file including the highlighted KO? Is that possible at all?

Something like

`wget https://www.genome.jp/pathway/ko02024+K07173`

does not work.

Is there any option in `bioservices` that facilitates that?

**Comment by cokelaer** [comment]
Dear @willigott 

It is possibble. I have done for example in sequana.readthedocs.io (sequana/enrichment.kegg.py). It was not included in bioservices because every users tend to wish different version of this function.

If you want to do it yourself, you first need to post what you want. And from the response, get the image, finally you need to save it. So, not that straightfoward...  

I have included a save_pathway command that should help you in version 1.8.3

**Comment by willigott** [comment]
Dear @cokelaer,

Thanks, that works nice indeed! One helpful addition would be to also have the `dcolor` argument available from `show_pathway` as now everything will be pink when different colors are used. If I find time, I might make a pull request.

Thanks for your great work!

In case anyone runs into this thread and wonders how to use the `save_pathway` function, here a minimal example:
```

from bioservices import KEGG

s = KEGG()

target_map = 'ko00340'
target_kos = ['K00765', 'K01814']
s.save_pathway(target_map, 'test.png', keggid=target_kos)
```

**Comment by willigott** [comment]
Seems this functionality has stopped working. When using the exact same code as above I now still get a png, but the KOs are not colored pink anymore. Here a link it creates in `save_pathway`: https://www.kegg.jp//kegg/pathway/ko/ko00340.png?16973792913422371

When doing it "by hand" it still looks fine (https://www.genome.jp/pathway/ko00340+K00765+K01814), so the KOs are still correct.

Any ideas what might have changed in the KEGG API?
