### ISSUE TITLE
pip install throws an OSError for version 1.10.1

### ISSUE THREAD

**Issue by jeeva2812** [cokelaer/bioservices#235]
ERROR: Could not install packages due to an OSError: [Errno 22] Invalid argument: 'C:\\Users\\Jeeva\\AppData\\Local\\Temp\\pip-install-el6nj1_1\\bioservices_5b97b3f8037a4d3e8e982453414883ce\\.github/workflows/:'

pip install of previous versions works fine though.

Tried using pip 22.1 and python 3.8

**Comment by cokelaer** [comment]
I have tested the install with pip 22.2.2 and python3.7. Seems to work. 
Similarly with python3.8. I have updated the MANIFEST and will push a release in a few days. We'll see if it solves your problem. I have indeed added a new directory .github/workflows that I may omit for pip installation. Maybe the .github is not welcome on windows platform.

**Comment by iawbrooks** [comment]
I have the exact same error on Windows 11 for pip 22.2.2 and Python 3.9.

**Comment by cokelaer** [comment]
I've just release a new version on pypi (v1.10.2a). @iawbrooks @jeeva2812 could you please have a go using

    pip install bioservices --upgrade

thanks in advance.best

**Comment by joaquinabian** [comment]
I found same problem today
Windows10, Python3.8, pip 22.2.2

Used both:
pip install bioservices
pip install bioservices --no-cache-dir
pip install bioservices --upgrade

Always got something like (from last one)

`Collecting bioservices
  Using cached bioservices-1.10.1.tar.gz (964 kB)
ERROR: Could not install packages due to an OSError: [Errno 22] Invalid argument: 'C:\\Users\\joaquin\\AppData\\Local\\Temp\\pip-install-wf6kwp8e\\bioservices_8e8cc33e6eea49498a96aacf23013d76\\.github/workflows/:'`

**Comment by cokelaer** [comment]
@joaquinabian sorry the version 1.10.2 was not on pypi, so you tried with the same version. I have now uploaded v1.10.2 if you want to to try again ?

**Comment by jeeva2812** [comment]
Tested it out on a Windows machine. The bug seems to be resolved. Closing the issue. If it persists for anyone @iawbrooks @joaquinabian, feel free to reopen. Thank you so much @cokelaer
