### ISSUE TITLE
bioservics Panther

### ISSUE THREAD

**Issue by liz-procogia** [cokelaer/bioservices#255]
Cannot access class Panther from Bioservices,  possible typo with what module its attached to ( bioservics vs bioservices)

**Comment by cokelaer** [comment]
Dear @liz-procogia the Panther service is known to be down from time to time. The class should work. I have been using it regularly during the last years within the sequana.readthedocs.io project especially on enrichement for RNA-seq analysis. As I said it is known to be down from time to time. Please retry; If unsucessful, please  provide a script/example so that I can double check your script (if needed). best
