### ISSUE TITLE
Get PDB IDs from Ensembl gene name, gene ID or transcript ID?

### ISSUE THREAD

**Issue by tommycarstensen** [cokelaer/bioservices#86]
Is it possible to use bioservices to get PDB IDs from an Ensembl gene name (e.g. TNFRSF18), gene ID (e.g. ENSG00000186891) or transcript ID (e.g. ENST00000328596)?

**Comment by cokelaer** [comment]
Your best option is BioDBNet. I had to rewrite it because the API changed but this is not pushed to the master. This is not available yet on pypi or bioconda but from the github master only.

However, on your example there is no PDB ID but in theory this shoudl work. You may use the dbFind method or the dbReport, which is longer but exhaustive:

    >>> from bioservices import BioDBNet
    >>> b = BioDBNet(cache=True)
    >>> df = b.dbReport("Ensembl Gene ID", ['ENSG00000186891'])
    >>> df[["PDB ID", "Gene ID", "Ensembl Transcript ID"]].T
    Ensembl Gene ID                                          ENSG00000186891
    PDB ID                                                                 -
    Gene ID                                                             8784
    Ensembl Transcript ID  ENST00000328596//ENST00000379268//ENST00000486...


note that this services is a bit slow.
